import AddPlayer_role from "../Components/player_role/AddPlayer_role";

export const ROUTES = {
  DASHBOARD: "/dashboard",
  LOGOUT: "/logout",
  BALL: "/ball",
  SEASON_COMPETITOR_PLAYER: "/season_competitor_player",
  STAGES: "/stages",
  TOURNAMENT_INFORMATION: "/tournament_information",
  TOURNAMENT_MATCH: "/tournament_match",
  COMPETITOR: "/competitor",
  PLAYER: "/player",
  PLAYER_ROLE: "/player_role",
  ADD_ROLE: "/add_role",
  EDIT_ROLE: "/edit_role/:id",
  DELETEPLAYER_ROLE: "/delete_player_role",

  CONTINENT: "/continent",
  DELETE_CONTINENT: "/delete_continent",
  EDIT_CONTINENT: "/edit_continent/:id",
  ADD_CONTINENT: "/add_continent",

  COUNTRY: "/country",
  DELETE_COUNTRY: "/delete_country",
  EDIT_COUNTRY: "/edit_country/:id",
  ADD_COUNTRY: "/add_country",
  ADD_BALL: "/add_ball",
  EDIT_BALL: "/edit_ball",
  DELETE_BALL: "/delete_ball",
  ADD_MATCH: "/add_match",
  EDIT_MATCH: "/edit_match",
  DELETE_MATCH: "/delete_match",
  ADD_PLAYER: "/add_player",
  EDIT_PLAYER: "/edit_player /:id",
  DELETE_PLAYER: "/delete_player",
  ADD_TEAM: "/add_team",
  EDIT_TEAM: "/edit_team",
  DELETE_TEAM: "/delete_team",
  ADD_TOURNAMENT: "/add_tournament",
  EDIT_TOURNAMENT: "/edit_tournament",
  DELETE_TOURNAMENT: "/delete_tournament",
  COUNTRY: "/country",
  INNING_BATTING: "/inning_batting",
  INNING_BOWLING: "/inning_bowling",
  INNING_FIELDING: "/inning_fielding",
  MATCH_PLAYER: "/match_player",
  MATCH_STATUS: "/match_status",
  OFFICIALS: "/officials",
  ADD_OFFICIAL: "/add_official",
  EDIT_OFFICIAL: "/edit_official/:id",
  DELETE_OFFICIAL: "/delete_official",


  PLAYER_ROLE: "/player_role",
  SCORCARD_DETAIL: "/scorcard_detail",
  SCORCARD_INNING: "/scorcard_inning",
  SCORE: "/score",
  SEASON_COMPETITOR: "/season_competitor",
};
